# Source: collabora-online/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: collabora
    labels:
        helm.sh/chart: collabora-online-1.1.21
        app.kubernetes.io/name: collabora-online
        app.kubernetes.io/instance: collabora-online
        app.kubernetes.io/version: 24.04.7.2.1
        app.kubernetes.io/managed-by: Helm
data:
    username: ENC[AES256_GCM,data:fcYFpsctToZgIf/FigA5KS4GlEPy8IGvtXVBM+Eejas=,iv:2hmzSGWDhCRf/UtgaywWhsQQzUpVrKnx+rjbptjsGD8=,tag:Gt3lHjTvj6i/uVkNQSK4Ig==,type:str]
    password: ENC[AES256_GCM,data:0lrNT//I1kAtSas3Mb9pwxG8lmkApsId2cH1asl5b0nyZmQY4FntVOAlMRmWO2CjNNMa58GLz+4=,iv:gtq3EIhw7+qlNTHXmvv+/L8zx0gMUynZbv3xBRhV3vo=,tag:q6oZa3TQfoQfYfIt/GgEoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArczZpb0xPNUp3ZnZsSjNr
            ZkgxWXZzNW5uSkNhOUU5eGhGLzBaQWFjTkhVClZCaDJJOTlNTzdqNytsbFd4QjNs
            eGthcEh2SU9Ed1ZLNkdZWVFWcnRYRjQKLS0tIHBDdnpldGYrWDZNTkI3dUtYWHVQ
            WERWaUZmWmdKaXhqUytGSHZ3KzhIMmcK2djki32gn1lxGB7PPp+npL2ZlyzWadEP
            90aBEhnhg5HGMXgCGiHqTuTQf9PqUZKAnNuBvRs0j0E7icQ1BduEaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T19:51:32Z"
    mac: ENC[AES256_GCM,data:y4Q9caNDurYh0QZ0w/WlweV+UbUqaMuZWbfafqbmJFvkDvW6MffGDmbnz/pOH4h4zg4iybq6aG7gT/039cmDnr1enu5kbcV3lMoPtgmOWSqfhzfQCHcq2Uj2JIbEp/LSIRJC1WDdxn2dCV9rnaJP/++l535AoEKrYzGfwstsILY=,iv:46Xj/psErde5tGr9CQANxd0p+06P47FywrsdcH/L8og=,tag:uPJ7aM1KSt36kSvUj7qY2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
