# Source: collabora-online/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: collabora
    labels:
        helm.sh/chart: collabora-online-1.1.21
        app.kubernetes.io/name: collabora-online
        app.kubernetes.io/instance: collabora-online
        app.kubernetes.io/version: 24.04.7.2.1
        app.kubernetes.io/managed-by: Helm
data:
    username: ENC[AES256_GCM,data:ooNSdLhk9kZq5Pxsi737uF2BN0v/pryq4yVXi5jpuUo=,iv:zjB+siQae4jmIWziuRjwfhox/4wrF43I9HdAsl/gW5M=,tag:qvm6cBBJ76r49XKzsdii4A==,type:str]
    password: ENC[AES256_GCM,data:hFUhmUTyqchQQHOEHyXekiIHLWUlC4/Oua8TuxrrZ8XVEEIu9Y9dG2sfO7tc4CJO+ypfiiK6JHM=,iv:s6ZC8ferwnAyLUMkEHwqGaDJeZNzX/eAIcaZN1sDt5E=,tag:VqGJPNjfDcNV0naEK57IxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRitLY2ZhMUxCbzc4MTBV
            OHdWU2phZ0pHekswYitUWG9vaXA5Mmd2b1d3CkJoQk1MUGVQblkrdklBaU5HRHY2
            Wkdoc3NaOVBWbjF3YmxVV3VnLzI1encKLS0tIDhzS1FscWNBdENwcUdESzF6d3o5
            MVhmbmFHcWozZy9NMk9kZU1qdld1ZU0KF73PiqmP0Jk6Y70I/09A0nDsPaNagLZV
            uId8bvAqmFXIPam7/tJc+y7YWmiBRqayy8XgAYUYvoVQ2UOQByRX0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T09:34:08Z"
    mac: ENC[AES256_GCM,data:5E6F5mM+mvdPnDmFwUCyf0aaZQLNxM5DB4tnoRPN6OKOTE7/8P6HKs85GRmyHSVvmg5OfVqs9NIdrf2pEmxZ6PgpA5zztsLHv6SwT9hsDiUxc12NdAq8gNuv6dNqhzg6uV59VRh/bYbH8188WGjjMQ3dKcUA6+BNjo8u2xK+AHk=,iv:dFLTsJaO/q6Eaqua9ECepbXPBSuPJES8I4xdGc0QyPY=,tag:4zjCKTsSmGLJOIJcKeO7Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
