# Source: opendesk-jitsi/charts/jitsi/charts/prosody/templates/envs-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody
    labels:
        helm.sh/chart: prosody-1.4.1
        app.kubernetes.io/name: prosody
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
type: Opaque
data: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUm14VW1CZkF0dVhaL2Rr
            WlZQaG1oVmd5Nm1rODRNbmQ2L3BKcEh5WkdrClNONFZhRlRzNzYzY05YMzN0RWwz
            Q2Y3WHl1TkpRSjgvbDJ5TjN6WFMvTFEKLS0tIGx1VjRYU21sVkRaUDFWaVExWjdk
            NjhMa3NyamwzdmdLTUM0MnFlT3BCNHMKcGTcZRoZ1glLK7OFqA1OjJAn5d4dCyON
            7eqDDv20svnDI9XHkzqa7jjYBZPrDORyHtaXJTsRsf8cPtZjonLD2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T05:49:48Z"
    mac: ENC[AES256_GCM,data:m0DhrEq0GwKsffIbmqhgYhgb9WMVz9tnFJtbUbH3ktclGwpqVqWthsoWXiluoGbUo/GA394TZK/sE4e5KAkWmIGlaDnEXgePx9CHdZjTd5iua189MrKOfdQsqqtQ6V4CJrD3zuBwl1C0N81TfCkKIHv2+GaKzUcc5BUzWFgwy/c=,iv:nROwgFV3S7O1kkAvpFc79bPSXLYDz0JoMCyXLxKU2d4=,tag:0MGsE3iMRfN36DteZE70/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jibri/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jibri
    labels:
        helm.sh/chart: jitsi-1.4.1
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jibri
type: Opaque
data:
    JIBRI_XMPP_USER: ENC[AES256_GCM,data:+X6eRiMhccM=,iv:dpKVsZRcP9Syy6w7Sx47Z5xbHyeX9klRhHbU1yR0fh8=,tag:U1IrYBtZPTFX2F/i9xff8A==,type:str]
    JIBRI_XMPP_PASSWORD: ENC[AES256_GCM,data:w4dG4e3oxWI0tKPmQ76hQgLyVBXeYVyklWolQo0K6xyHkhJHyUHEgvvPJqqf0Kp809FbX/lfAUU=,iv:FU/l2f2T/hIB78JQ05qCGhQxz10HjQTFw55TAM3zTzM=,tag:AVRT+S4ELF+iZF33aHMFcg==,type:str]
    JIBRI_RECORDER_USER: ENC[AES256_GCM,data:2fGvT5U6hsSGxi+S,iv:tP1CpVocnEX4TsB4cgBYuOL6pcRV6EOQE1RN5vDvdmw=,tag:1G5XwEj/aKmHJCfiF+qAMQ==,type:str]
    JIBRI_RECORDER_PASSWORD: ENC[AES256_GCM,data:/EQiPD9cHoV7RAGfKe3D7EN2IwyLBHVWUzZ9Hq1urwBt8ZxwWuNHasLY0rNZN1yyATLljDcvzrs=,iv:o+xNIwmohoJVVysHVz/s77SMG2pPEX8Rg6o45b3BLDc=,tag:96tUTl9Hx/XrsrrHvKk7iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUm14VW1CZkF0dVhaL2Rr
            WlZQaG1oVmd5Nm1rODRNbmQ2L3BKcEh5WkdrClNONFZhRlRzNzYzY05YMzN0RWwz
            Q2Y3WHl1TkpRSjgvbDJ5TjN6WFMvTFEKLS0tIGx1VjRYU21sVkRaUDFWaVExWjdk
            NjhMa3NyamwzdmdLTUM0MnFlT3BCNHMKcGTcZRoZ1glLK7OFqA1OjJAn5d4dCyON
            7eqDDv20svnDI9XHkzqa7jjYBZPrDORyHtaXJTsRsf8cPtZjonLD2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T05:49:48Z"
    mac: ENC[AES256_GCM,data:m0DhrEq0GwKsffIbmqhgYhgb9WMVz9tnFJtbUbH3ktclGwpqVqWthsoWXiluoGbUo/GA394TZK/sE4e5KAkWmIGlaDnEXgePx9CHdZjTd5iua189MrKOfdQsqqtQ6V4CJrD3zuBwl1C0N81TfCkKIHv2+GaKzUcc5BUzWFgwy/c=,iv:nROwgFV3S7O1kkAvpFc79bPSXLYDz0JoMCyXLxKU2d4=,tag:0MGsE3iMRfN36DteZE70/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jicofo/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jicofo
    labels:
        helm.sh/chart: jitsi-1.4.1
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jicofo
type: Opaque
data:
    JICOFO_AUTH_USER: ENC[AES256_GCM,data:ajy3tzvg+y8=,iv:aj2/Lmr363MasmLDFQtSPmLsE/R9Vp85OkK0gSEZLdU=,tag:7mrj4CUniJVqhI7Cq7gPbQ==,type:str]
    JICOFO_AUTH_PASSWORD: ENC[AES256_GCM,data:4+BdVD8ClTKGFAYGh9Kd5n4hhtO+X/bae8cRarg2DjQkPjV1IckcJVOiwYWafRuCPzWnp9btFBw=,iv:HbcS8MZRUwYmsgxdQYu3hshaPSntivNJBF3MDld51dQ=,tag:DVgan7IACGZWBgSRLkU9nQ==,type:str]
    JICOFO_COMPONENT_SECRET: ENC[AES256_GCM,data:2MgAkDl4sJVfZ5rRtQ4TqmdipS4YxTVJtJQIpcRlbg+YYN6zjUhmam0c4fwUkzk+mC7HyStoSCc=,iv:U3BvaZUmGYRkLHGnRuVLsJHOtbjmdl1g8EsriEbcf/E=,tag:ERSVpL3uR9YKfYK2IasEoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUm14VW1CZkF0dVhaL2Rr
            WlZQaG1oVmd5Nm1rODRNbmQ2L3BKcEh5WkdrClNONFZhRlRzNzYzY05YMzN0RWwz
            Q2Y3WHl1TkpRSjgvbDJ5TjN6WFMvTFEKLS0tIGx1VjRYU21sVkRaUDFWaVExWjdk
            NjhMa3NyamwzdmdLTUM0MnFlT3BCNHMKcGTcZRoZ1glLK7OFqA1OjJAn5d4dCyON
            7eqDDv20svnDI9XHkzqa7jjYBZPrDORyHtaXJTsRsf8cPtZjonLD2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T05:49:48Z"
    mac: ENC[AES256_GCM,data:m0DhrEq0GwKsffIbmqhgYhgb9WMVz9tnFJtbUbH3ktclGwpqVqWthsoWXiluoGbUo/GA394TZK/sE4e5KAkWmIGlaDnEXgePx9CHdZjTd5iua189MrKOfdQsqqtQ6V4CJrD3zuBwl1C0N81TfCkKIHv2+GaKzUcc5BUzWFgwy/c=,iv:nROwgFV3S7O1kkAvpFc79bPSXLYDz0JoMCyXLxKU2d4=,tag:0MGsE3iMRfN36DteZE70/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jigasi/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jigasi
    labels:
        helm.sh/chart: jitsi-1.4.1
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jigasi
type: Opaque
data: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUm14VW1CZkF0dVhaL2Rr
            WlZQaG1oVmd5Nm1rODRNbmQ2L3BKcEh5WkdrClNONFZhRlRzNzYzY05YMzN0RWwz
            Q2Y3WHl1TkpRSjgvbDJ5TjN6WFMvTFEKLS0tIGx1VjRYU21sVkRaUDFWaVExWjdk
            NjhMa3NyamwzdmdLTUM0MnFlT3BCNHMKcGTcZRoZ1glLK7OFqA1OjJAn5d4dCyON
            7eqDDv20svnDI9XHkzqa7jjYBZPrDORyHtaXJTsRsf8cPtZjonLD2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T05:49:48Z"
    mac: ENC[AES256_GCM,data:m0DhrEq0GwKsffIbmqhgYhgb9WMVz9tnFJtbUbH3ktclGwpqVqWthsoWXiluoGbUo/GA394TZK/sE4e5KAkWmIGlaDnEXgePx9CHdZjTd5iua189MrKOfdQsqqtQ6V4CJrD3zuBwl1C0N81TfCkKIHv2+GaKzUcc5BUzWFgwy/c=,iv:nROwgFV3S7O1kkAvpFc79bPSXLYDz0JoMCyXLxKU2d4=,tag:0MGsE3iMRfN36DteZE70/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jvb/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jvb
    labels:
        helm.sh/chart: jitsi-1.4.1
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jvb
type: Opaque
data:
    JVB_AUTH_USER: ENC[AES256_GCM,data:dEyMrA==,iv:JmtTOJOimIPjTLX55+mtSns9jeCX1HiBX8NnwrhyJPk=,tag:f/FheuRo3IX0Oj7g0SWJZw==,type:str]
    JVB_AUTH_PASSWORD: ENC[AES256_GCM,data:5BgzVHi2Yck8lkCYw4E9YRHWW85HDKsNITeZdxiX22lc1o4Qbu9iHk4vQlRuXwSO7DH+rzHtQtE=,iv:XVtAONSIkSht0387mR8IjV+8ZXuASMt9gjUkWl2bpsM=,tag:ajS8uZgtCBHN6iiQ3JMC3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUm14VW1CZkF0dVhaL2Rr
            WlZQaG1oVmd5Nm1rODRNbmQ2L3BKcEh5WkdrClNONFZhRlRzNzYzY05YMzN0RWwz
            Q2Y3WHl1TkpRSjgvbDJ5TjN6WFMvTFEKLS0tIGx1VjRYU21sVkRaUDFWaVExWjdk
            NjhMa3NyamwzdmdLTUM0MnFlT3BCNHMKcGTcZRoZ1glLK7OFqA1OjJAn5d4dCyON
            7eqDDv20svnDI9XHkzqa7jjYBZPrDORyHtaXJTsRsf8cPtZjonLD2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T05:49:48Z"
    mac: ENC[AES256_GCM,data:m0DhrEq0GwKsffIbmqhgYhgb9WMVz9tnFJtbUbH3ktclGwpqVqWthsoWXiluoGbUo/GA394TZK/sE4e5KAkWmIGlaDnEXgePx9CHdZjTd5iua189MrKOfdQsqqtQ6V4CJrD3zuBwl1C0N81TfCkKIHv2+GaKzUcc5BUzWFgwy/c=,iv:nROwgFV3S7O1kkAvpFc79bPSXLYDz0JoMCyXLxKU2d4=,tag:0MGsE3iMRfN36DteZE70/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-opendesk-jitsi-keycloak-adapter
    namespace: tn-openbsw-opendesk
    labels:
        app.kubernetes.io/name: opendesk-jitsi
        helm.sh/chart: opendesk-jitsi-3.0.1
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/managed-by: Helm
stringData:
    jwtAppSecret: ENC[AES256_GCM,data:QWtOyCwC+as8dVbmoCFR58hVR4/Vbpn9SmrNYX+NoIUF+HU72ld5Iw==,iv:8r4d4tH9s2yToVfYuDhhFfwhcAxq09lHNqbWLlTRt7Y=,tag:gONyQORPOlZRx0O8U6nTrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUm14VW1CZkF0dVhaL2Rr
            WlZQaG1oVmd5Nm1rODRNbmQ2L3BKcEh5WkdrClNONFZhRlRzNzYzY05YMzN0RWwz
            Q2Y3WHl1TkpRSjgvbDJ5TjN6WFMvTFEKLS0tIGx1VjRYU21sVkRaUDFWaVExWjdk
            NjhMa3NyamwzdmdLTUM0MnFlT3BCNHMKcGTcZRoZ1glLK7OFqA1OjJAn5d4dCyON
            7eqDDv20svnDI9XHkzqa7jjYBZPrDORyHtaXJTsRsf8cPtZjonLD2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T05:49:48Z"
    mac: ENC[AES256_GCM,data:m0DhrEq0GwKsffIbmqhgYhgb9WMVz9tnFJtbUbH3ktclGwpqVqWthsoWXiluoGbUo/GA394TZK/sE4e5KAkWmIGlaDnEXgePx9CHdZjTd5iua189MrKOfdQsqqtQ6V4CJrD3zuBwl1C0N81TfCkKIHv2+GaKzUcc5BUzWFgwy/c=,iv:nROwgFV3S7O1kkAvpFc79bPSXLYDz0JoMCyXLxKU2d4=,tag:0MGsE3iMRfN36DteZE70/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
