# Source: opendesk-jitsi/charts/jitsi/charts/prosody/templates/envs-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody
    labels:
        helm.sh/chart: prosody-1.3.8
        app.kubernetes.io/name: prosody
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9111
        app.kubernetes.io/managed-by: Helm
type: Opaque
data: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ejc5enV2ZysrOVBrd1J4
            V2xIQjQrcUJOT0tGWUxremd2dVFkNkYyVFh3CmxZZktIRkhQbDh4K3VhbVVUK2FI
            anNWK0xpbFJmeGZ5cGNVWG9UNmdLckUKLS0tICtDaURtbEhWRWxzb1FXMVpoSk5B
            MHJSUkhxbUtYVUQ2QnZuOGM4Qm5QQkEK4Q7LdfANub8YmuR4oqqqXSejC9vznPRK
            Mw3sXTh77NWKPRrZtN69KGHBleapKD6WkzaUngnVd/2oac5p0QM/XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T09:34:08Z"
    mac: ENC[AES256_GCM,data:EYZuPqSgkLgc63hVBHkZE0l2Xgic7pVFbztesl7fcRp8EDJQKxPyHezi/ba08cn2XfkWtAQvqwboW5odaBPobPdHG5b7wTDBhvHTzCDPp6OM1SAiSZsQGtrsVUHYFqK3xfuWRdXYKLCkurNXXj3jqnHnufHza/LDp/GTGTUF/z0=,iv:3Xl2yfTzbxeGXhVsyhqgImsAgL7WsZ4Q189+GN+ZStA=,tag:OIBLWVQHCiaYhfGhM1cxfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jibri/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jibri
    labels:
        helm.sh/chart: jitsi-1.3.8
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9111
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jibri
type: Opaque
data:
    JIBRI_XMPP_USER: ENC[AES256_GCM,data:0asIaNfZIaE=,iv:ZVBOBvUfBCMY79ezRDoYQe3YgN3PnnCTneb+fE1h98g=,tag:MGSm6mbWgssX3nB8Qcz5mQ==,type:str]
    JIBRI_XMPP_PASSWORD: ENC[AES256_GCM,data:zeR5wTznOQ3oY1q2kfv06nUHRQf3eFui9ljOnJG6/8xw0bTo8Gm1EjFX8jSxLNhS8iTmi2Agopo=,iv:V4Rw6P5ugIkfGZIFktkSEYRYpyA401NW6CrQyxetnAk=,tag:mHk2dAQa9wAi/KjpSWvU0w==,type:str]
    JIBRI_RECORDER_USER: ENC[AES256_GCM,data:R+l4bm5H72/ivPHR,iv:h6wIwP1M0tzQbgbzyww4xjQr5KRHt5juXwLRiaEQafs=,tag:NOhZnq3E2iol2vdFnvGVNw==,type:str]
    JIBRI_RECORDER_PASSWORD: ENC[AES256_GCM,data:zKVcxT7az2q5HnwSgi6gOLK7vlHHZcLxy81Jx1KUxi6kx1PURA80phMsIEVkTRqzrhNlJks5/Gk=,iv:EHznGLenVU0x8M8t/N+7qC9ohXVU3eem9y0NKAKPKI8=,tag:pZ0QVdl3OP26Fc3LtXOj8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ejc5enV2ZysrOVBrd1J4
            V2xIQjQrcUJOT0tGWUxremd2dVFkNkYyVFh3CmxZZktIRkhQbDh4K3VhbVVUK2FI
            anNWK0xpbFJmeGZ5cGNVWG9UNmdLckUKLS0tICtDaURtbEhWRWxzb1FXMVpoSk5B
            MHJSUkhxbUtYVUQ2QnZuOGM4Qm5QQkEK4Q7LdfANub8YmuR4oqqqXSejC9vznPRK
            Mw3sXTh77NWKPRrZtN69KGHBleapKD6WkzaUngnVd/2oac5p0QM/XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T09:34:08Z"
    mac: ENC[AES256_GCM,data:EYZuPqSgkLgc63hVBHkZE0l2Xgic7pVFbztesl7fcRp8EDJQKxPyHezi/ba08cn2XfkWtAQvqwboW5odaBPobPdHG5b7wTDBhvHTzCDPp6OM1SAiSZsQGtrsVUHYFqK3xfuWRdXYKLCkurNXXj3jqnHnufHza/LDp/GTGTUF/z0=,iv:3Xl2yfTzbxeGXhVsyhqgImsAgL7WsZ4Q189+GN+ZStA=,tag:OIBLWVQHCiaYhfGhM1cxfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jicofo/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jicofo
    labels:
        helm.sh/chart: jitsi-1.3.8
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9111
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jicofo
type: Opaque
data:
    JICOFO_AUTH_USER: ENC[AES256_GCM,data:4Wn4Is91CV4=,iv:sIJ4Pn/bNTOSeBCKZVpIgCpZcjx20QKuBXT5F0bk/VM=,tag:cAyngXXDWwRY0At4HRne9g==,type:str]
    JICOFO_AUTH_PASSWORD: ENC[AES256_GCM,data:wA/7BoW5tlosOXztJ5oElmKO0RVYeaw2IRjSwKVa1wTTZlPjvzTvkzLFY8mhBjgx+sys298m6ug=,iv:WvmfBpjW4UKI+S8hjXFIJAhIz078+oz+J0x9wOPJYOk=,tag:edL5enof8sF3LtnL1MCSZg==,type:str]
    JICOFO_COMPONENT_SECRET: ENC[AES256_GCM,data:y41YyOqrqrGD8XcCcKr3jJQBSOXnD5jKGr2/9y7aZlpttS7OpEJQ7Ed5MVSij6+X93yqQXrMpzc=,iv:E3kVYeHGFgyOI+hlt7t+TiYtUmfqfEuXzh/1xG6890k=,tag:ZkDTBYy0zoS1QZI5YB46Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ejc5enV2ZysrOVBrd1J4
            V2xIQjQrcUJOT0tGWUxremd2dVFkNkYyVFh3CmxZZktIRkhQbDh4K3VhbVVUK2FI
            anNWK0xpbFJmeGZ5cGNVWG9UNmdLckUKLS0tICtDaURtbEhWRWxzb1FXMVpoSk5B
            MHJSUkhxbUtYVUQ2QnZuOGM4Qm5QQkEK4Q7LdfANub8YmuR4oqqqXSejC9vznPRK
            Mw3sXTh77NWKPRrZtN69KGHBleapKD6WkzaUngnVd/2oac5p0QM/XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T09:34:08Z"
    mac: ENC[AES256_GCM,data:EYZuPqSgkLgc63hVBHkZE0l2Xgic7pVFbztesl7fcRp8EDJQKxPyHezi/ba08cn2XfkWtAQvqwboW5odaBPobPdHG5b7wTDBhvHTzCDPp6OM1SAiSZsQGtrsVUHYFqK3xfuWRdXYKLCkurNXXj3jqnHnufHza/LDp/GTGTUF/z0=,iv:3Xl2yfTzbxeGXhVsyhqgImsAgL7WsZ4Q189+GN+ZStA=,tag:OIBLWVQHCiaYhfGhM1cxfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jvb/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jvb
    labels:
        helm.sh/chart: jitsi-1.3.8
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9111
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jvb
type: Opaque
data:
    JVB_AUTH_USER: ENC[AES256_GCM,data:ywXbtw==,iv:Z+Ydw18o5+wj7pWYV56hq1CaUtGYUz9lD7rKcCmyEQA=,tag:Vh7QDGOsnoCkR1vprT+Szg==,type:str]
    JVB_AUTH_PASSWORD: ENC[AES256_GCM,data:8rpPl53NTr1c8YOiLNO/rEvuUuMVnWEx7VPfd0CPBtjrKLoKaUGAgI8cNABHDV7SwZNGjgkURqo=,iv:jbs95qPO8NrhbpVfdMxI7W2Q50Hh9SNs8BzVWPqCSgE=,tag:CPao3+Z0/T9ZTNLT3xwSMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ejc5enV2ZysrOVBrd1J4
            V2xIQjQrcUJOT0tGWUxremd2dVFkNkYyVFh3CmxZZktIRkhQbDh4K3VhbVVUK2FI
            anNWK0xpbFJmeGZ5cGNVWG9UNmdLckUKLS0tICtDaURtbEhWRWxzb1FXMVpoSk5B
            MHJSUkhxbUtYVUQ2QnZuOGM4Qm5QQkEK4Q7LdfANub8YmuR4oqqqXSejC9vznPRK
            Mw3sXTh77NWKPRrZtN69KGHBleapKD6WkzaUngnVd/2oac5p0QM/XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T09:34:08Z"
    mac: ENC[AES256_GCM,data:EYZuPqSgkLgc63hVBHkZE0l2Xgic7pVFbztesl7fcRp8EDJQKxPyHezi/ba08cn2XfkWtAQvqwboW5odaBPobPdHG5b7wTDBhvHTzCDPp6OM1SAiSZsQGtrsVUHYFqK3xfuWRdXYKLCkurNXXj3jqnHnufHza/LDp/GTGTUF/z0=,iv:3Xl2yfTzbxeGXhVsyhqgImsAgL7WsZ4Q189+GN+ZStA=,tag:OIBLWVQHCiaYhfGhM1cxfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
