# Source: opendesk-jitsi/charts/jitsi/charts/prosody/templates/envs-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody
    labels:
        helm.sh/chart: prosody-1.4.1
        app.kubernetes.io/name: prosody
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
type: Opaque
data: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWJKSnA4SnJXRGQ2YkZZ
            T3h2dGc5YzFtSHZjUmZSNVZiekphRFN6SmtjCnNldStIZXdCbEtxdEV3OHM0WG9q
            ZE1WS3o2ckFKVVNIZXNlODlEMUN1UEEKLS0tIERLa1B1ZjNRaUNpelNCK21uUVRr
            RUdML1RhbW5xNmM3Z1ZOMjdEREcrekUKS95ksETqyo4F+GK/ZHW14J6OoE43IQZa
            0hGI2lCO4y55krYhY5C0zUdzpVxdWoBZHHCRtsF+eXJhaEdGD+PWTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T19:51:32Z"
    mac: ENC[AES256_GCM,data:ERco0amGjnV9lTZjc9dSd0K3k4EMjYNTXElfi0fSxF/G0pOdD0uW6T6iNHh9oayWgTD3b4Qjb10qYaeXnGdaWttdoqdhr7yQIkuyUv/VzyTfNazOC0CEAQtWQ8OzqFU3IyQlCMTREh275L7aFmZ5SXS8ImY180Lz764PGr8I4ss=,iv:FevzNnqg4CNV5c2ceizWd5FBBSgZZSr012hkIoPvjMI=,tag:5FTPOKubwLL0PN8eGuOTwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jibri/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jibri
    labels:
        helm.sh/chart: jitsi-1.4.1
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jibri
type: Opaque
data:
    JIBRI_XMPP_USER: ENC[AES256_GCM,data:EHAzo2xJ2aU=,iv:Chnda4dvnVS0YnEWIbtb1kKbJQ9s1K/9lQgmdq7Z57I=,tag:gVvhBelHfUBt80M2jfng/Q==,type:str]
    JIBRI_XMPP_PASSWORD: ENC[AES256_GCM,data:gWP0GR3RTmZWL/6fTRYJP2M6QlCV35taRn/MILwzgwuMDjHDD8mvohiFLdV1cxu1J/lZCL7oVCg=,iv:yl47GshLzaUnTDUVrmfs3ZVwpDTl66vvT1BO7LFDU58=,tag:pG2sIY/YhVa9CLzPQBvqUw==,type:str]
    JIBRI_RECORDER_USER: ENC[AES256_GCM,data:STCT9Qg4APQU4iX8,iv:Y2K9z7/6vPCXYGZyPIpwWlcWSNNh5eH9+eLy3V/F2jY=,tag:rgx1sTXoRN4M8VqM7ko9kg==,type:str]
    JIBRI_RECORDER_PASSWORD: ENC[AES256_GCM,data:vb2rX4hgLiqLxPqWxwZ2kIYhO3N2MLHHLRmyIKfntqLB6wZ6Gy4pWRE27gagq7/V5z9zlG0YyzI=,iv:DXxpD1p6rXK1Ag3iyXr92EdWR2gKWreKDoGQVbAGCAU=,tag:UoAdieSg9eVpHiTQnXAI6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWJKSnA4SnJXRGQ2YkZZ
            T3h2dGc5YzFtSHZjUmZSNVZiekphRFN6SmtjCnNldStIZXdCbEtxdEV3OHM0WG9q
            ZE1WS3o2ckFKVVNIZXNlODlEMUN1UEEKLS0tIERLa1B1ZjNRaUNpelNCK21uUVRr
            RUdML1RhbW5xNmM3Z1ZOMjdEREcrekUKS95ksETqyo4F+GK/ZHW14J6OoE43IQZa
            0hGI2lCO4y55krYhY5C0zUdzpVxdWoBZHHCRtsF+eXJhaEdGD+PWTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T19:51:32Z"
    mac: ENC[AES256_GCM,data:ERco0amGjnV9lTZjc9dSd0K3k4EMjYNTXElfi0fSxF/G0pOdD0uW6T6iNHh9oayWgTD3b4Qjb10qYaeXnGdaWttdoqdhr7yQIkuyUv/VzyTfNazOC0CEAQtWQ8OzqFU3IyQlCMTREh275L7aFmZ5SXS8ImY180Lz764PGr8I4ss=,iv:FevzNnqg4CNV5c2ceizWd5FBBSgZZSr012hkIoPvjMI=,tag:5FTPOKubwLL0PN8eGuOTwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jicofo/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jicofo
    labels:
        helm.sh/chart: jitsi-1.4.1
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jicofo
type: Opaque
data:
    JICOFO_AUTH_USER: ENC[AES256_GCM,data:MQvyAnowa5w=,iv:nQ9g1BlHZzo9d8NoJ4LzeqGxRKghsJnPFvHhGa4Hdz0=,tag:Rwdia38NimLvSJU/dOzeBQ==,type:str]
    JICOFO_AUTH_PASSWORD: ENC[AES256_GCM,data:aRF4o6ZuwRsmAltd3tg3j/lQru4lrUzAkvxH2bduPr3zZ72JbEn6kOow5omZGAazpyFjsl9lmR4=,iv:BTv6Sl4Fvi1qKLnpqSCiyRe6395BaDfCNDJubYCY+NU=,tag:yTCbmWpXIpdQJx1Fx7t10w==,type:str]
    JICOFO_COMPONENT_SECRET: ENC[AES256_GCM,data:fEX5iWjX+0G0QbMq/8x5cMw0Uqs/MN0NPhvR4IWWJou1wAHULZBpkM/IulTlGH7aKCLH1SLfzCY=,iv:WtLILEMhgrPSqcEG62/5GpIyF3pX3nro4AodzNTzv/A=,tag:HZmp1VoUDodu3L63L1Fw+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWJKSnA4SnJXRGQ2YkZZ
            T3h2dGc5YzFtSHZjUmZSNVZiekphRFN6SmtjCnNldStIZXdCbEtxdEV3OHM0WG9q
            ZE1WS3o2ckFKVVNIZXNlODlEMUN1UEEKLS0tIERLa1B1ZjNRaUNpelNCK21uUVRr
            RUdML1RhbW5xNmM3Z1ZOMjdEREcrekUKS95ksETqyo4F+GK/ZHW14J6OoE43IQZa
            0hGI2lCO4y55krYhY5C0zUdzpVxdWoBZHHCRtsF+eXJhaEdGD+PWTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T19:51:32Z"
    mac: ENC[AES256_GCM,data:ERco0amGjnV9lTZjc9dSd0K3k4EMjYNTXElfi0fSxF/G0pOdD0uW6T6iNHh9oayWgTD3b4Qjb10qYaeXnGdaWttdoqdhr7yQIkuyUv/VzyTfNazOC0CEAQtWQ8OzqFU3IyQlCMTREh275L7aFmZ5SXS8ImY180Lz764PGr8I4ss=,iv:FevzNnqg4CNV5c2ceizWd5FBBSgZZSr012hkIoPvjMI=,tag:5FTPOKubwLL0PN8eGuOTwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jigasi/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jigasi
    labels:
        helm.sh/chart: jitsi-1.4.1
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jigasi
type: Opaque
data: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWJKSnA4SnJXRGQ2YkZZ
            T3h2dGc5YzFtSHZjUmZSNVZiekphRFN6SmtjCnNldStIZXdCbEtxdEV3OHM0WG9q
            ZE1WS3o2ckFKVVNIZXNlODlEMUN1UEEKLS0tIERLa1B1ZjNRaUNpelNCK21uUVRr
            RUdML1RhbW5xNmM3Z1ZOMjdEREcrekUKS95ksETqyo4F+GK/ZHW14J6OoE43IQZa
            0hGI2lCO4y55krYhY5C0zUdzpVxdWoBZHHCRtsF+eXJhaEdGD+PWTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T19:51:32Z"
    mac: ENC[AES256_GCM,data:ERco0amGjnV9lTZjc9dSd0K3k4EMjYNTXElfi0fSxF/G0pOdD0uW6T6iNHh9oayWgTD3b4Qjb10qYaeXnGdaWttdoqdhr7yQIkuyUv/VzyTfNazOC0CEAQtWQ8OzqFU3IyQlCMTREh275L7aFmZ5SXS8ImY180Lz764PGr8I4ss=,iv:FevzNnqg4CNV5c2ceizWd5FBBSgZZSr012hkIoPvjMI=,tag:5FTPOKubwLL0PN8eGuOTwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/charts/jitsi/templates/jvb/xmpp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-prosody-jvb
    labels:
        helm.sh/chart: jitsi-1.4.1
        app.kubernetes.io/name: jitsi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/version: stable-9646
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jvb
type: Opaque
data:
    JVB_AUTH_USER: ENC[AES256_GCM,data:PPAe9w==,iv:2nLW9qF3JsCSO+fKDSb0zaM4uFlcnfuQlTjHFpw8iTE=,tag:cBN2Z1TYpT7HeXfQ96NsTA==,type:str]
    JVB_AUTH_PASSWORD: ENC[AES256_GCM,data:uChAoYXMQJvVBUrRLKqVSFKQEAGW+WmytlbptnvNPDb2Q18XG5Ii7kLT7tBSnphv5jPInXYPJhg=,iv:FVWfRJNBCoaOzoXg992/CN/0Af/a/VOYNlh/esuzMqQ=,tag:dh2lQ+W7aW+wfIsoaR4w4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWJKSnA4SnJXRGQ2YkZZ
            T3h2dGc5YzFtSHZjUmZSNVZiekphRFN6SmtjCnNldStIZXdCbEtxdEV3OHM0WG9q
            ZE1WS3o2ckFKVVNIZXNlODlEMUN1UEEKLS0tIERLa1B1ZjNRaUNpelNCK21uUVRr
            RUdML1RhbW5xNmM3Z1ZOMjdEREcrekUKS95ksETqyo4F+GK/ZHW14J6OoE43IQZa
            0hGI2lCO4y55krYhY5C0zUdzpVxdWoBZHHCRtsF+eXJhaEdGD+PWTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T19:51:32Z"
    mac: ENC[AES256_GCM,data:ERco0amGjnV9lTZjc9dSd0K3k4EMjYNTXElfi0fSxF/G0pOdD0uW6T6iNHh9oayWgTD3b4Qjb10qYaeXnGdaWttdoqdhr7yQIkuyUv/VzyTfNazOC0CEAQtWQ8OzqFU3IyQlCMTREh275L7aFmZ5SXS8ImY180Lz764PGr8I4ss=,iv:FevzNnqg4CNV5c2ceizWd5FBBSgZZSr012hkIoPvjMI=,tag:5FTPOKubwLL0PN8eGuOTwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# Source: opendesk-jitsi/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: jitsi-opendesk-jitsi-keycloak-adapter
    namespace: tn-openbsw-opendesk
    labels:
        app.kubernetes.io/name: opendesk-jitsi
        helm.sh/chart: opendesk-jitsi-3.0.1
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/managed-by: Helm
stringData:
    jwtAppSecret: ENC[AES256_GCM,data:p7GJ6p5uLiMiu6ZfUAQTubavoJxY2rCKCVM3KlQ8NnUTZ/wY4wYQTw==,iv:eaZOqgcPQzrkoFxenwbnJFNnXG9HkrTMugrogzFd9bk=,tag:0X1y1q6a/iTO36f5GmxucA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l0ly6j6p08tqwr0p2zp9899597cdqh9m27wa3lapy60nlvyx2gvqq5azhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWJKSnA4SnJXRGQ2YkZZ
            T3h2dGc5YzFtSHZjUmZSNVZiekphRFN6SmtjCnNldStIZXdCbEtxdEV3OHM0WG9q
            ZE1WS3o2ckFKVVNIZXNlODlEMUN1UEEKLS0tIERLa1B1ZjNRaUNpelNCK21uUVRr
            RUdML1RhbW5xNmM3Z1ZOMjdEREcrekUKS95ksETqyo4F+GK/ZHW14J6OoE43IQZa
            0hGI2lCO4y55krYhY5C0zUdzpVxdWoBZHHCRtsF+eXJhaEdGD+PWTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T19:51:32Z"
    mac: ENC[AES256_GCM,data:ERco0amGjnV9lTZjc9dSd0K3k4EMjYNTXElfi0fSxF/G0pOdD0uW6T6iNHh9oayWgTD3b4Qjb10qYaeXnGdaWttdoqdhr7yQIkuyUv/VzyTfNazOC0CEAQtWQ8OzqFU3IyQlCMTREh275L7aFmZ5SXS8ImY180Lz764PGr8I4ss=,iv:FevzNnqg4CNV5c2ceizWd5FBBSgZZSr012hkIoPvjMI=,tag:5FTPOKubwLL0PN8eGuOTwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
