# Source: opendesk-migrations/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opendesk-migrations-post
  namespace: tn-openbsw-opendesk
  labels:
    app.kubernetes.io/name: opendesk-migrations
    helm.sh/chart: opendesk-migrations-1.3.5
    app.kubernetes.io/instance: opendesk-migrations-post
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: opendesk-migrations/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opendesk-migrations-post
  labels:
    app.kubernetes.io/name: opendesk-migrations
    helm.sh/chart: opendesk-migrations-1.3.5
    app.kubernetes.io/instance: opendesk-migrations-post
    app.kubernetes.io/managed-by: Helm
rules:
  #
  # All Migrations: Allow self management of configmap
  #
- apiGroups: ['']
  resources: [configmaps]
  verbs: [create]
- apiGroups: ['']
  resources: [configmaps]
  resourceNames: [migrations-status]
  verbs: ['*']
  #
  # run_2.py
  #
  # Delete of StatefulSet ox-connector.
- apiGroups: [apps]
  resources: [statefulsets]
  resourceNames: [ox-connector]
  verbs: [delete]
  # Delete services ums-keycloak, ums-udm-rest-api
- apiGroups: ['']
  resources: [services]
  resourceNames: [ums-keycloak, ums-udm-rest-api]
  verbs: [delete]
  # Delete old "hooked" OX bootstrap job
- apiGroups: [batch]
  resources: [jobs]
  resourceNames: [opendesk-open-xchange-bootstrap]
  verbs: [delete]
  # Delete deployment ums-umc-server
- apiGroups: [apps]
  resources: [deployments]
  resourceNames: [ums-umc-server]
  verbs: [delete]
  # Execute slacpcat in LDAP Pod
- apiGroups: ['']
  resources: [pods/exec]
  resourceNames: [ums-ldap-server-0]
  verbs: [get, create]
  # PVC get (current size of)
- apiGroups: ['']
  resources: [persistentvolumeclaims]
  resourceNames: [shared-data-ums-ldap-server-0, ox-connector-ox-contexts-ox-connector-0]
  verbs: [get]
  # Rescaling of LDAP stateful sets before copying the PVC.
- apiGroups: [apps]
  resources: [statefulsets/scale]
  resourceNames: [ums-ldap-notifier, ums-ldap-server]
  verbs: [get, update, patch]
  # PVC create [with copy].
- apiGroups: ['']
  resources: [persistentvolumeclaims]
  verbs: [create]
  # PVC delete that are no longer in use.
- apiGroups: ['']
  resources: [persistentvolumeclaims]
  resourceNames: [shared-data-ums-ldap-server-0, shared-run-ums-ldap-server-0, ox-connector-appcenter-ox-connector-0,
    ox-connector-data-ox-connector-0, ox-connector-ox-contexts-ox-connector-0]
  verbs: [delete]
  # Restart of Deployments.
- apiGroups: [apps]
  resources: [deployments]
  resourceNames: [ums-keycloak, opendesk-nextcloud-php, ums-umc-server]
  verbs: [update, patch]
  # Restart of StatefulSets.
- apiGroups: [apps]
  resources: [statefulsets]
  resourceNames: [ums-selfservice-listener, opendesk-synapse]
  verbs: [update, patch]
---
# Source: opendesk-migrations/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opendesk-migrations-post
  labels:
    app.kubernetes.io/name: opendesk-migrations
    helm.sh/chart: opendesk-migrations-1.3.5
    app.kubernetes.io/instance: opendesk-migrations-post
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opendesk-migrations-post
subjects:
- kind: ServiceAccount
  name: opendesk-migrations-post
---
# Source: opendesk-migrations/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: opendesk-migrations-post-1
  labels:
    app.kubernetes.io/name: opendesk-migrations
    helm.sh/chart: opendesk-migrations-1.3.5
    app.kubernetes.io/instance: opendesk-migrations-post
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished:
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: opendesk-migrations
        helm.sh/chart: opendesk-migrations-1.3.5
        app.kubernetes.io/instance: opendesk-migrations-post
        app.kubernetes.io/managed-by: Helm
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: opendesk-migrations-post
      containers:
      - name: opendesk-migrations
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seLinuxOptions:
          seccompProfile:
            type: RuntimeDefault
        image:
          registry.opencode.de/bmi/opendesk/components/platform-development/images/opendesk-migrations:1.3.18@sha256:d7f13322cc9cc7ab157f926280070850b0dfc6169c93a306ec4c3cf7c21eff69
        imagePullPolicy: IfNotPresent
        command:
        - /app/odmigs.py
        volumeMounts:
        - name: environmentdetails-volume
          mountPath: /app/etc/
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: MIGRATIONS_LOGLEVEL
          value: INFO
        - name: MIGRATIONS_CLEANUP
          value: 'false'
        - name: MIGRATIONS_STAGE
          value: POST
        - name: MIGRATIONS_RUN_ID
          value: '2'
        - name: MIGRATIONS_NAMESPACE
          value: 'tn-openbsw-opendesk'
        - name: MIGRATIONS_FAIL_ON_UNEXPECTED_STATE
          value: 'true'
      volumes:
      - name: environmentdetails-volume
        secret:
          secretName: opendesk-migrations-post-environmentdetails
