# Source: opendesk-migrations/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opendesk-migrations-post
  namespace: tn-openbsw-opendesk
  labels:
    app.kubernetes.io/name: opendesk-migrations
    helm.sh/chart: opendesk-migrations-1.4.0
    app.kubernetes.io/instance: opendesk-migrations-post
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: opendesk-migrations/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opendesk-migrations-post
  labels:
    app.kubernetes.io/name: opendesk-migrations
    helm.sh/chart: opendesk-migrations-1.4.0
    app.kubernetes.io/instance: opendesk-migrations-post
    app.kubernetes.io/managed-by: Helm
rules:
  #
  # All Migrations: Allow self management of configmap
  #
- apiGroups: ['']
  resources: [configmaps]
  verbs: [create]
- apiGroups: ['']
  resources: [configmaps]
  resourceNames: [migrations-status]
  verbs: ['*']
  #
  # run_3.py
  #
  # Add UMS LDAP ConfigMap.
  # Ref.: https://docs.software-univention.de/nubus-kubernetes-release-notes/1.5.1/en/changelog.html#migrate-existing-ldap-server-to-mirror-mode-readiness
- apiGroups: ['']
  resources: [configmaps]
  resourceNames: [ums-ldap-server-status]
  verbs: [create]
---
# Source: opendesk-migrations/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opendesk-migrations-post
  labels:
    app.kubernetes.io/name: opendesk-migrations
    helm.sh/chart: opendesk-migrations-1.4.0
    app.kubernetes.io/instance: opendesk-migrations-post
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opendesk-migrations-post
subjects:
- kind: ServiceAccount
  name: opendesk-migrations-post
---
# Source: opendesk-migrations/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: opendesk-migrations-post-1
  labels:
    app.kubernetes.io/name: opendesk-migrations
    helm.sh/chart: opendesk-migrations-1.4.0
    app.kubernetes.io/instance: opendesk-migrations-post
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: opendesk-migrations
        helm.sh/chart: opendesk-migrations-1.4.0
        app.kubernetes.io/instance: opendesk-migrations-post
        app.kubernetes.io/managed-by: Helm
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: opendesk-migrations-post
      containers:
      - name: opendesk-migrations
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seLinuxOptions:
          seccompProfile:
            type: RuntimeDefault
        image:
          registry.opencode.de/bmi/opendesk/components/platform-development/images/opendesk-migrations:1.4.0@sha256:0c74011e4c1216857b73695741196908afcacc2f531fd1c894b8f574ac98f9a2
        imagePullPolicy: IfNotPresent
        command:
        - /app/odmigs.py
        volumeMounts:
        - name: environmentdetails-volume
          mountPath: /app/etc/
          readOnly: true
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: MIGRATIONS_LOGLEVEL
          value: DEBUG
        - name: MIGRATIONS_CLEANUP
          value: 'false'
        - name: MIGRATIONS_STAGE
          value: POST
        - name: MIGRATIONS_RUN_ID
          value: '3'
        - name: MIGRATIONS_NAMESPACE
          value: 'tn-openbsw-opendesk'
        - name: MIGRATIONS_FAIL_ON_UNEXPECTED_STATE
          value: 'true'
      volumes:
      - name: environmentdetails-volume
        secret:
          secretName: opendesk-migrations-post-environmentdetails
