apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postfix
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2023.12.20
    helm.sh/chart: minio-12.10.11
  name: minio
  namespace: tn-openbsw-opendesk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: matrix-neodatefix-bot
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix-neodatefix-bot
    helm.sh/chart: matrix-neodatefix-bot-3.5.0
  name: matrix-neodatefix-bot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
